docs: extend python cookbook
jdx/mise pull request #3738
Opened 2024-12-20 14:16 UTC by Finkregh

2024-12-20 14:17 UTC, Finkregh commented
I did not get passing args via `depends=`, perhaps someone could fix that? :)

2024-12-20 17:59 UTC, jdx requested changes

2024-12-20 17:59 UTC, jdx commented on docs/mise-cookbook/python.md
> +Recommended configuration
I certainly don't "recommend" this

2024-12-20 17:59 UTC, jdx commented on docs/mise-cookbook/python.md
> +```tomo [~/.config/mise/config.toml]
typo

2024-12-20 17:59 UTC, jdx commented on docs/mise-cookbook/python.md
> +enter = "mise i -q && mise plugins update"
doesn't seem like this should go into the python cookbook

2024-12-20 17:59 UTC, jdx commented on docs/mise-cookbook/python.md
> +#XXMISEXX depends=["preset:python"]
this would need to be resolved first

2024-12-20 17:59 UTC, jdx commented on docs/mise-cookbook/python.md
> +mise config set tasks.install_deps.description "Install dependencies"
`mise task add` is a better way to do this

2024-12-20 17:59 UTC, jdx commented on docs/mise-cookbook/python.md
> +mise tasks run -vvv preset:python 3.13
why -vvv?

2024-12-20 18:52 UTC, Finkregh commented on docs/mise-cookbook/python.md
> +mise tasks run -vvv preset:python 3.13
Missed that, thx

2024-12-21 15:53 UTC, hverlin commented on docs/mise-cookbook/python.md
> +## Using tasks to create mise.toml for individual projects
Maybe some of this content should go to https://mise.jdx.dev/mise-cookbook/presets.html, it also describes something similar. We can probably link it from the python cookbook page

2024-12-24 15:34 UTC, oefe commented on docs/mise-cookbook/python.md
> +mise config set hooks.enter "uv pip sync pyproject.toml"
`uv pip sync` uses uv as a pip replacement, it's not intended for uv-managed projects.

Did you mean to use `uv sync`?

2025-03-21 16:17 UTC, jdx commented
closing due to inactivity

2025-03-21 16:17 UTC, closed without merging